### ISSUE TITLE
[BUG] `ssx.signIn()` with custom routes invokes the login route.

### ISSUE THREAD

**Issue by Prithpal-Sooriya** [spruceid/ssx#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When performing a `signOut()` with custom routes set, the custom `/login` route is hit.

Snippet:
```typescript
import { SSX } from "@spruceid/ssx";

// ...
function createSSX() {
  return new SSX({
    providers: {
      server: {
        host: "http://localhost:3001",
        routes: {
          login: "/login",
          logout: "/logout",
          nonce: "/nonce",
        },
      },
    }
  })
}

// ...
const ssxLogoutHandler = async () => {
  await ssxProvider?.signOut();
  setSSX(null);
  window.ssx = null;
};
```

### Expected Behavior

The custom route `/logout`, should be used.

### Steps To Reproduce

1. Setup a server on using custom endpoints
2. Create a simple client app using `"@spruceid/ssx"` package.
3. Setup the custom routes
4. Try the `.signOut()` method

### Anything else?

Think it is related to this:
https://github.com/spruceid/ssx/blob/main/packages/ssx-sdk/src/core.ts#L328

Where we need to change the route to be `logout` instead of `login`
```diff
-  const route = this.config.providers?.server?.routes?.login ?? '/ssx-logout';
+  const route = this.config.providers?.server?.routes?.logout ?? '/ssx-logout';
```

**Comment by samgbafa** [comment]
Hey @Prithpal-Sooriya! This was fixed in #140!
